/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Ad: typeof import('./views/ad/index.vue')['default']
    Admin: typeof import('./views/admin/index.vue')['default']
    App: typeof import('./views/app/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    EpDelete: typeof import('~icons/ep/delete')['default']
    EpEdit: typeof import('~icons/ep/edit')['default']
    EpFullScreen: typeof import('~icons/ep/full-screen')['default']
    EpPlus: typeof import('~icons/ep/plus')['default']
    EpRefresh: typeof import('~icons/ep/refresh')['default']
    EpVideoCameraFilled: typeof import('~icons/ep/video-camera-filled')['default']
    Home: typeof import('./views/home/index.vue')['default']
    Live: typeof import('./views/movie/live.vue')['default']
    Login: typeof import('./views/user/login.vue')['default']
    Logo: typeof import('./layout/logo/index.vue')['default']
    Menu: typeof import('./layout/menu/index.vue')['default']
    Movie: typeof import('./views/movie/index.vue')['default']
    Role: typeof import('./views/admin/role.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestCom: typeof import('./components/testCom/index.vue')['default']
    Toolbar: typeof import('./layout/toolbar/index.vue')['default']
    User: typeof import('./views/user/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
